global using Xunit;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using MyStore.Controllers;
global using MyStore.Pages;
global using MyStore.Models;
global using MyStore.Models.Cart;
global using MyStore.Models.Repository;
global using MyStore.Models.ViewModels;